Rails/blog/config/routes.rb
Rails.application.routes.draw do

  get 'mypage/test'

  get 'welocme/index'

  resources :articles

  root 'welcome#index'

end

Rails/blog/app/models/article.rb
class Article < ActiveRecord::Base
end

Rails/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new 
    end 
    def create
        #render plain: params[:article].inspect
        @article = Article.new(params[:article])

        @article.save
        redirect_to @article

    end 
end

Rails/blog/app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def test
  end
end

Rails/blog/app/controllers/welocme_controller.rb
class WelocmeController < ApplicationController
  def index
  end
end

Rails/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Rails/blog/app/helpers/mypage_helper.rb
module MypageHelper
end

Rails/blog/app/helpers/welocme_helper.rb
module WelocmeHelper
end

Rails/blog/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

Rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Rails/blog/app/views/mypage/test.html.erb
<h1>Mypage#test</h1>
<p>Find me in app/views/mypage/test.html.erb</p>

Rails/blog/app/views/welocme/index.html.erb
<h1>Hello, Rails!</h1>